FROM node:20-alpine

# Setup buildtime environment variables with defaults
ARG ENVIRONMENT=staging
ENV ENVIRONMENT=${ENVIRONMENT}
ARG SENTRY_SUPPRESS_TURBOPACK_WARNING=true
ENV SENTRY_SUPPRESS_TURBOPACK_WARNING=${SENTRY_SUPPRESS_TURBOPACK_WARNING}
ARG NEXT_PUBLIC_SENTRY_DSN=""
ENV NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}
ARG NEXT_PUBLIC_API_BASE_URL=""
ENV NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
ARG NEXT_PUBLIC_PROJECT_NAME="coolnomix"
ENV NEXT_PUBLIC_PROJECT_NAME=${NEXT_PUBLIC_PROJECT_NAME}

# Add a work directory
WORKDIR /app

# Copy package.json and yarn.lock files
COPY package.json yarn.lock ./

# Install dependencies with production flag and clean cache
RUN yarn install --frozen-lockfile --production=false && \
    yarn cache clean

# Copy only necessary files for build
COPY next.config.ts ./
COPY tsconfig.json ./
COPY postcss.config.mjs ./
COPY tailwind.config.ts ./
COPY src ./src
COPY app ./app
COPY messages ./messages
COPY middleware.ts ./

# Clean the .next directory if exists
RUN rm -rf .next

# Build the application for production with increased memory limit
RUN yarn build

# Expose the port the app runs on
EXPOSE 3000

# Define the command to run the app. Use "yarn start" for production.
CMD ["yarn", "start"]
