FROM node:16-alpine AS development
ENV NODE_ENV development

# Add cache directory to install package
WORKDIR /cache

# Install dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn install

# Add a work directory
WORKDIR /app

# Copy app files
COPY . .

# Run the app
ENTRYPOINT ["/app/.docker/start.dev.sh"]
