FROM node:16-alpine AS builder
ENV NODE_ENV production

# Setup buildtime environment variables
ARG ENVIRONMENT=${ENVIRONMENT}
ENV ENVIRONMENT=${ENVIRONMENT}
ARG NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
ENV NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
ARG NEXT_PUBLIC_POSTHOG_HOST=${NEXT_PUBLIC_POSTHOG_HOST}
ENV NEXT_PUBLIC_POSTHOG_HOST=${NEXT_PUBLIC_POSTHOG_HOST}
ARG SENTRY_DSN=${SENTRY_DSN}
ENV SENTRY_DSN=${SENTRY_DSN}
ARG API_BASE_URL=${API_BASE_URL}
ENV API_BASE_URL=${API_BASE_URL}

# Add a work directory
WORKDIR /app

# Cache and Install dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn install --production

# Copy app files
COPY . .

# Build the app
RUN yarn build

# Bundle static assets with nginx
FROM nginx:1.23-alpine as production
ENV NODE_ENV production

# Copy built assets from builder
COPY --from=builder /app/dist /etc/nginx/html

# Add your nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
