name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy-to-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Caprover
        run: npm install -g caprover

      - name: Deploy
        run: caprover deploy -h '${{ secrets.CAPROVER_ROOT_URL }}' -p '${{ secrets.CAPROVER_PASSWORD }}' -b 'stg' -a 'dashboard'
